[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Near Node Flash (NNF)"
authors = [{name = "Hewlett Packard Enterprise", email = "noreply@hpe.com"}]
dynamic = ["version", "description"]
